name: pia
description: public transport interchange assistance.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.1
  logging: ^1.2.0
  http: ^1.1.0
  latlong2: ^0.9.0
  maps_toolkit: ^3.0.0
  maplibre_gl: 0.19.0+2
  flutter_mvvm_architecture:
    git:
      url: https://github.com/Robbendebiene/flutter-mvvm-architecture.git
  get_it: ^7.6.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  hive_flutter: ^1.1.0
  flutter_material_design_icons: ^1.1.7296
  moment_dart: ^1.1.0
  render_metrics: ^2.0.2
  app_links: ^6.1.4
  geolocator: ^13.0.1
  easylocate_flutter_sdk:
    path: ./easylocate_flutter_sdk
  flutter_localizations:
    sdk: flutter
  intl: any

# To prevent version solving in PIA
dependency_overrides:
    # easyLocateFlutterSDK depends on older meta version
    meta: 1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/app_icon.png'

flutter:
  uses-material-design: true
  generate: true

assets:
