name: ptia
description: public transport interchange assistance.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  maplibre_gl:
    git:
      url: https://github.com/m0nac0/flutter-maplibre-gl.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
